services:
  - type: web
    name: busca-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "cd busca_api && python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn busca_api.wsgi:application --bind 0.0.0.0:$PORT"
